dist: xenial
language: generic
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar
  xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal test --haddock --no-haddock-deps
-
before_deploy:
- zip -r $TRAVIS_COMMIT .
- mkdir -p upload
- mv $TRAVIS_COMMIT.zip upload/$TRAVIS_COMMIT.zip
deploy:
- provider: s3
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: N6O9uwwGQ/p7T6mLeRl5YQq7j6dSbEvUdYCQdyDSSocwiyJHsSgPhx2xElGp7rg/zZK4zhrj0Ez6NyDtKbbR//YAig2LR/f1DtmpHWRAJHklUWM5plAJGezp+Rihxi/TeiJUsXdGvg7QkACbQDB/ikkIUbjqIqhnLynUEd/E6AKc1lvds3UsvHcct/nbZKZ4ETO9UlBl3e3ZuEDEYxPWeBpb2lcx9q+8pYE/JBMymOi5vEGclXmYSR/KQ63uTyOC2yycxVIiFyItI204N0HGffypKpiEpyqQK0AKkEq7XK8EPrldpx791ZoGjA4+thwwSFJi6jcA3sl9/cI6lzENst/DZD2r/hXcYf+JRAHbK1XOwdUXB+toeSZNQkGy3qdsjSj9m42JglySyyImX1O0C+zYPq/4Tq0P+T/yIULKBq//fU9dT8mAU2Vpep+MwjNyl1s1UXFEVsrfFt18mTVnQ+0NwSqeMHROmzMb0CnebMF8R/IqLApSNOjKUkdQW8fzovInj9qvmY683rEr2Otd6c0UK8b6w8BVJrRpulQ60eG1Ktzq+eZRj5PYGvhHaOcpSJ+GxhMM4IOiNhC8XXChsA6kWHfmfjx8UbOVv1NZcmSTW9/w7M5wt8sAib4r/fnty9CjUqcyYp5NJOXLvd4aFgVuadQUCfc3E28RHSoLL3U=
  skip_cleanup: true
  local_dir: upload
  bucket: tslaq-deployments
  upload-dir: tslaq-prices
  dot_match: true
  acl: private
  on:
    repo: amiri/tslaq-prices
- provider: codedeploy
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: N6O9uwwGQ/p7T6mLeRl5YQq7j6dSbEvUdYCQdyDSSocwiyJHsSgPhx2xElGp7rg/zZK4zhrj0Ez6NyDtKbbR//YAig2LR/f1DtmpHWRAJHklUWM5plAJGezp+Rihxi/TeiJUsXdGvg7QkACbQDB/ikkIUbjqIqhnLynUEd/E6AKc1lvds3UsvHcct/nbZKZ4ETO9UlBl3e3ZuEDEYxPWeBpb2lcx9q+8pYE/JBMymOi5vEGclXmYSR/KQ63uTyOC2yycxVIiFyItI204N0HGffypKpiEpyqQK0AKkEq7XK8EPrldpx791ZoGjA4+thwwSFJi6jcA3sl9/cI6lzENst/DZD2r/hXcYf+JRAHbK1XOwdUXB+toeSZNQkGy3qdsjSj9m42JglySyyImX1O0C+zYPq/4Tq0P+T/yIULKBq//fU9dT8mAU2Vpep+MwjNyl1s1UXFEVsrfFt18mTVnQ+0NwSqeMHROmzMb0CnebMF8R/IqLApSNOjKUkdQW8fzovInj9qvmY683rEr2Otd6c0UK8b6w8BVJrRpulQ60eG1Ktzq+eZRj5PYGvhHaOcpSJ+GxhMM4IOiNhC8XXChsA6kWHfmfjx8UbOVv1NZcmSTW9/w7M5wt8sAib4r/fnty9CjUqcyYp5NJOXLvd4aFgVuadQUCfc3E28RHSoLL3U=
  bucket: tslaq-deployments
  bundle_type: zip
  key: tslaq-prices/$TRAVIS_COMMIT.zip
  application: tslaq-prices
  deployment_group: tslaq-prices
  wait_until_deployed: true
