dist: xenial
language: generic
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar
  xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal test --haddock --no-haddock-deps
- 
before_deploy:
- zip -r $TRAVIS_COMMIT .
- mkdir -p upload
- mv $TRAVIS_COMMIT.zip upload/$TRAVIS_COMMIT.zip
deploy:
- provider: s3
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: K3iOC5hmNdcdnEx7XBoVZLCuiBxIkrO9p3Qnm5yBfs0SZkIBCd1mViKBYojFytPSvNqgah4PR0huk4mrxPMNoHa70Rba7+x4nWkC/NqL6gWqT1ZYnaepoHirgXEHaDtD6xfk0WCfpxsjJ1g0v1hyscdGVkuPZ2bkid99lYmzmFI47pvlPPqDuDtAksoYx+swFjPZo72ujjhAU0Oo/5GqiXoIY5r5AjHyAmLTXKBEFW0hjTS2PWqLitno4b+YIgAPl+3aaZT2bnrFNNWUAVkjsEy2/Mv8uU08z804tfpr6raVqfq/gOibQXk8KDo6qj6DfKcJnbMBk14M4cjWsBzVuJhEAP+nEn9WyhDv7FA4yvOjimKeH4P8ffo8S2hxWmtUWn9Qy+EUOZle7xlFVk6Is6UIayleQjIMrR+ZGI07lclExJj9fFpvNwBZEPNcUdznvNB3EQvjR8bNtpCjc5QcIy1trUzm10zkzDZ44LHqBLju08a6Fp+HAKAeIyr1K1sEEtyfcoGj/4/S3Pn7FfZcRS82E0s7ffos4gcBZ12LQ2YBhdOIkD5pAJmA3eTk1SIdGnNEJIgyAahcmaxahjzXWASI0K7NwoW8cthXiR0kRI2UWxEH25S2gGwzUrSpR07FydvA6xOIzhXw+OdVqPCZMP8YC0bSd+4SaUPBD771xQk=
  skip_cleanup: true
  local_dir: upload
  bucket: tslaq-deployments
  upload-dir: tslaq-prices
  dot_match: true
  acl: private
  on:
    repo: amiri/tslaq-prices
- provider: codedeploy
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: K3iOC5hmNdcdnEx7XBoVZLCuiBxIkrO9p3Qnm5yBfs0SZkIBCd1mViKBYojFytPSvNqgah4PR0huk4mrxPMNoHa70Rba7+x4nWkC/NqL6gWqT1ZYnaepoHirgXEHaDtD6xfk0WCfpxsjJ1g0v1hyscdGVkuPZ2bkid99lYmzmFI47pvlPPqDuDtAksoYx+swFjPZo72ujjhAU0Oo/5GqiXoIY5r5AjHyAmLTXKBEFW0hjTS2PWqLitno4b+YIgAPl+3aaZT2bnrFNNWUAVkjsEy2/Mv8uU08z804tfpr6raVqfq/gOibQXk8KDo6qj6DfKcJnbMBk14M4cjWsBzVuJhEAP+nEn9WyhDv7FA4yvOjimKeH4P8ffo8S2hxWmtUWn9Qy+EUOZle7xlFVk6Is6UIayleQjIMrR+ZGI07lclExJj9fFpvNwBZEPNcUdznvNB3EQvjR8bNtpCjc5QcIy1trUzm10zkzDZ44LHqBLju08a6Fp+HAKAeIyr1K1sEEtyfcoGj/4/S3Pn7FfZcRS82E0s7ffos4gcBZ12LQ2YBhdOIkD5pAJmA3eTk1SIdGnNEJIgyAahcmaxahjzXWASI0K7NwoW8cthXiR0kRI2UWxEH25S2gGwzUrSpR07FydvA6xOIzhXw+OdVqPCZMP8YC0bSd+4SaUPBD771xQk=
  bucket: tslaq-deployments
  bundle_type: zip
  key: tslaq-prices/$TRAVIS_COMMIT.zip
  application: tslaq-prices
  deployment_group: tslaq-prices
  wait_until_deployed: true
