name:                tslaq-prices
version:             0.1.0.0
github:              "amiri/tslaq-prices"
license:             BSD3
author:              "Amiri Barksdale"
maintainer:          "amiribarksdale@gmail.com"
copyright:           "2019 Amiri Barksdale"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/amiri/tslaq-prices#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- amazonka
- amazonka-core
- amazonka-s3
- amazonka-secretsmanager
- aws-easy
- bytestring
- cassava
- conduit
- containers
- directory
- filepath
- hslogger
- lens
- lens-aeson
- monad-control
- mtl
- pureMD5
- regex-pcre
- resourcet
- safe
- split
- text
- time
- timezone-olson
- timezone-series
- transformers
- unordered-containers
- vector
- wreq
- zip
library:
  source-dirs: src

executables:
  tslaq-prices-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options: '-ferror-spans -Werror -Wall -threaded -rtsopts "-with-rtsopts=-N -T"'
    dependencies:
    - tslaq-prices

tests:
  tslaq-prices-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: '-ferror-spans -Werror -Wall -threaded -rtsopts "-with-rtsopts=-N -T"'
    dependencies:
    - tslaq-prices
